### ISSUE TITLE
Add social network requirement

### ISSUE THREAD

**Issue by Swader** [hpoa/poa-faucet#1]
A user should be required to tweet something like:

> I'm using the Lisinski Faucet to get some Lisinski Ether for the Lisinski Testnet. More information at https://lisinski.online/en!

An SQLite or similar DB can make notes of which tweets have been used (consider the tweets UTXOs) so that a person can always be required to submit a new tweet before claiming eth. The end goal is making Lisinski popular.

Once implemented, raise the limit to 1 eth per request.

**Comment by mpetrunic** [comment]
It seens that twitter broke that 2 years ago, event is now fired when user clicks button, and not when he actually tweeted. Which means he can actually click button , close popup and faucet will still think that user has tweeted. Source: https://twittercommunity.com/t/forthcoming-change-to-web-intent-events/54718

We could, alternatively, implement Oauth twitter login and user their api directly, instead of widget button.

**Comment by Swader** [comment]
No need to rely on Twitter, faucet workflow should be changed to:

- 2 input fields available
- publish tweet
- enter tweet URL in one, and eth address in other
- request eth
- if tweet is unused and public, grant eth.

**Comment by mpetrunic** [comment]
Yeah, that would work, should we put like 24hour cooldown on tweeter username?

**Comment by Swader** [comment]
I'd say 4, maybe 8 h. The more #lisinski gets spammed out, the better for us :)
